jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

server:
  port: 8070

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  redis:
    host: localhost
    port: 6379
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.eazybytes.filter: DEBUG
