# Server Configuration
server:
  port: 8085

# Application Name (for Eureka and identification)
spring:
  application:
    name: payment-service
  config:
    import: "optional:configserver:http://config-service:8888"
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

  # MySQL Configuration (Primary Data Source)
  datasource:
      url: jdbc:mysql://mysql:3306/ecommerce_payment?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      username: tiendoan
      password: tiendoan
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  

  # Kafka Configuration (Producer for event-driven communication)
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.eazybytes.event.model.ProcessPaymentRequest
        spring.json.type.mapping: 
          process-payment-request:com.eazybytes.event.model.ProcessPaymentRequest,
          payment-succeeded:com.eazybytes.event.model.PaymentSucceededEvent,
          payment-failed:com.eazybytes.event.model.PaymentFailedEvent

kafka:
  topics:
    payment:
      process: process-payment-request
      succeeded: payment-succeeded
      failed: payment-failed


# Eureka Configuration (Service Discovery)
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


