server:
  port: 8100

spring:
  application:
    name: inventory-service
  config:
    import: "optional:configserver:http://config-service:8888"
  datasource:
    url: jdbc:mysql://mysql:3306/ecommerce_inventory?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: tiendoan
    password: tiendoan
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 15
      minimum-idle: 8
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
      connection-test-query: SELECT 1
      transaction-isolation: TRANSACTION_READ_COMMITTED

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        connection:
          provider_disables_autocommit: false
        jdbc:
          batch_size: 10
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
    deserialization:
      fail-on-unknown-properties: false

  mvc:
    async:
      request-timeout: 300000

  # Cấu hình Kafka
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: all
        retries: 3
    consumer:
      group-id: inventory-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: "java.util.HashMap"
        spring.json.remove.type.headers: false
        spring.json.deserialization.fail.on.unknown.properties: false
        spring.json.type.mapping: "reserve-inventory-request:com.eazybytes.dto.ReserveInventoryRequest,confirm-inventory-reservation:com.eazybytes.dto.ConfirmInventoryReservationRequest,cancel-inventory-reservation:com.eazybytes.dto.CancelInventoryReservationRequest"
        session.timeout.ms: 30000
        heartbeat.interval.ms: 10000
        max.poll.interval.ms: 300000
kafka:
  topics:
    inventory:
      reserved: inventory-reserved
      reservation-failed: inventory-reservation-failed
      confirmed: inventory-confirmed
    reserve-inventory-request: reserve-inventory-request
    confirm-inventory-reservation: confirm-inventory-reservation
    cancel-inventory-reservation: cancel-inventory-reservation
    checkout:
      failed: checkout-failed

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

logging:
  level:
    com.eazybytes: DEBUG
    org.springframework.kafka: INFO
    com.eazybytes.service.LLMService: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Inventory Service specific configuration
inventory:
  notification:
    low-stock-threshold: 5
    enable-email-alert: false
  metrics:
    enable: true

openai:
  api:
    key: '${OPENAI_API_KEY}'
    url: https://api.openai.com/v1/chat/completions
  model: gpt-4o-mini

# LLM Configuration
llm:
  enabled: true  # Set to true to enable OpenAI integration

