# Sử dụng base image vừa build
FROM ecommerce-website-chatbot-chatbot:latest 

WORKDIR /app

# RUN pip install pymongo


EXPOSE 5500

CMD ["uvicorn", "main:asgi_app", "--host", "0.0.0.0", "--port", "5500"]